/* Automatically generated by './build/bin/build-entry.js' */

import BaseInput from './packages/base-input/index.js';
import BackEndPagingTable from './packages/back-end-paging-table/index.js';
import FrontEndPagingTable from './packages/front-end-paging-table/index.js';
import SearchTable from './packages/search-table/index.js';
import ApiDataTable from './packages/api-data-table/index.js';
import DynamicForm from './packages/dynamic-form/index.js';
import GridTable from './packages/grid-table/index.js';
import DetailExtendForm from './packages/detail-extend-form/index.js';
import XForm from './packages/x-form/index.js';
import ExtendDetail from './packages/extend-detail/index.js';
import ExtendForm from './packages/extend-form/index.js';

const components = [
  BaseInput,
  BackEndPagingTable,
  FrontEndPagingTable,
  SearchTable,
  ApiDataTable,
  DynamicForm,
  GridTable,
  DetailExtendForm,
  XForm,
  ExtendDetail,
  ExtendForm,
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.16',
  install,
  BaseInput,
  BackEndPagingTable,
  FrontEndPagingTable,
  SearchTable,
  ApiDataTable,
  DynamicForm,
  GridTable,
  DetailExtendForm,
  XForm,
  ExtendDetail,
  ExtendForm
};
